### ISSUE TITLE
Make configuration easier

### ISSUE THREAD

**Issue by Blarc** [Blarc/gitlab-template-lint-plugin#103]
Try to make configuration more straightforward. Any ideas and suggestions are welcome.

From the review:
"Configuring this is a nightmare. Things named differently than in GitLab, wrong error prompts, no examples on what the author means by "GitLab URL". Didn't manage to even start this plugin."

**Comment by zartc** [comment]
That's right the vocabulary is not inline with the one used in GitLab, this is a shame.
Please follow this configuration page: [gitlab-permissions](https://screenful.com/gitlab/gitlab-permissions). What is explained there is applicable to this plugin.

**Comment by Blarc** [comment]
Would the following renamings provide more clear meaning?
- `Gitlab URL -> Gitlab API URL`
- `Remote ID -> Gitlab Project ID`
- `Gitlab Token -> Gitlab API Token`

Is there anything else that is confusing?

**Comment by zartc** [comment]
> Gitlab URL -> Gitlab API URL

Yes that's better, and give: `https://gitlab.com/api/v4` as an example or better yet as the default value in the plugin, because `https://gitlab.com` is too short and validation always failed with that shorter url (this is, IMHO, THE most confusing thing in the configuration).

> Remote ID -> Gitlab Project ID

Yes that is better

> Gitlab Token -> Gitlab API Token

No, this is called a `Gitlab Personal Access Tokens` for which only the `api` and the `read_api` scopes need to be granted (which makes it an api token de facto). Also you can mention that the generated token should start with the string: `glpat--`. This will reassure peoples that they have generated the correct token.

**Comment by Blarc** [comment]
I have released a new version [**1.8.0**](https://github.com/Blarc/gitlab-template-lint-plugin/releases/tag/v1.8.0)  that contains these changes. You can wait for JetBrains to aprove the new version and publish it on marketplace or install it manually by following [these](https://github.com/Blarc/ai-commits-intellij-plugin#installation-from-zip) steps.

I think it should be much clearer now. If not, please report back what else should I change. Thanks for the suggestions :pray: .

**Comment by Blarc** [comment]
Hey @ldaverio,

as @zartc mentioned, and he was clearly right that this isn't clear either, the plugin expects you to create `Personal Access Token`, which can be created [here](https://gitlab.com/-/profile/personal_access_tokens).

However, I believe project access token should work as well. The token however needs `api` and `read_api` scopes. Can you please try with these scopes and report back, if it doesn't work?

**Comment by ldaverio** [comment]
Hello, I deleted my previous post because I felt it wasn't really justified, I hadn't read the instructions carefully enough, my bad, all my apologies...

- All relevant fields were pre-filled with the correct values

- A project access token with the `api` and `read_api` permissions didn't work for me with the `guest` or `developer` roles, maybe it needs `maintaner`?

- I was able to create the right token by clicking on the provided link (see screenshot), a personal access token does work.

<img width="701" alt="Capture d’écran 2023-04-24 à 11 28 57" src="https://user-images.githubusercontent.com/8393625/233957187-2def9b9b-d888-4db4-8644-40f7dd6bc8ca.png">

**Comment by zartc** [comment]
> I have released a new version [1.8.0](https://github.com/Blarc/gitlab-template-lint-plugin/releases/tag/v1.8.0) that contains [these](https://github.com/Blarc/gitlab-template-lint-plugin#installation-from-zip) changes. You can wait for JetBrains to aprove the new version and publish it on marketplace or install it manually by following these steps.

> I think it should be much clearer now. If not, please report back what else should I change. Thanks for the suggestions 🙏 .

It is much clearer now and the `here` link to go directly to the PAT creation page is a **luminous idea**.

just one more thing though; When cliking the here button you direct the user to the PAT creation page of the `gitlab.com` instance. Why not pre-populate the _Gitlab API URL_ field with the value `https://gitlab.com/api/v4` verbatim. It would be that less to enter for the user. And if the user enters another URL to another instance of GitLab, don't forget to use the user specified URL to direct the user to the PAT page in his instance of GitLab when he clicks on the `here` link.

**Comment by Blarc** [comment]
@zartc Prepopulating the Gitlab API URL field is a great idea. Do you think I should rename the Gitlab API Token field to Gitlab Personal Access Token?

Updating the PAT url is sort of implemented already. The PAT url is computed from the url that is initially in the dialog or https://gitlab.com/-/profile/personal_access_tokens if no Gitlab API URL is specified. I was thinking of changing the PAT url whenever the value in Gitlab API URL field changes, but that is kind of tricky. What do you think?

**Comment by zartc** [comment]
> Do you think I should rename the Gitlab API Token field to Gitlab Personal Access Token?
I think "Gitlab API Token" is meaningful, so it is ok IMHO.

> I was thinking of changing the PAT url whenever the value in Gitlab API URL field changes, but that is kind of tricky. What do you think?
Simply recalculate the PAT URL at the time the user clicks the "here" link, taking what is currently in the "Gitlab API URL" field. But you might want to check the correctness of the url using java's http client and redirect to https://gitlab.com/-/profile/personal_access_tokens in case you get a 404

**Comment by Blarc** [comment]
The "here" link is actually a href html element, not a button. So I'm not sure if I can recalculate the URL on click, but maybe I could just change it to button. I'll try it, thanks.

**Comment by Blarc** [comment]
The creation of PAT link from Gitlab API url was added in version 1.9.0.
