### ISSUE TITLE
Сonsultation about included files

### ISSUE THREAD

**Issue by evsmorodin** [Blarc/gitlab-template-lint-plugin#153]
Hello!

Please help me! Whats wrong?

![изображение](https://github.com/Blarc/gitlab-template-lint-plugin/assets/7508931/69796ae5-bd35-47a7-9028-5415ef274212)

**Comment by Blarc** [comment]
Hey.

The problem is that file `.gitlab-ci/production.yml` does not exist on the remote branch. Try to commit and push the file to remote branch.

The GitLab lint API only accepts one file at a time, that's why the plugin only sends the current file: https://github.com/Blarc/gitlab-template-lint-plugin/issues/14.

Btw, path globs have nothing to do with `include` keyword. Path globs only tell the plugin which files to check. Sorry if it's a bit confusing, I could maybe add an additional comment.
